CREATE TABLE buckets (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL,
    description VARCHAR(4000),
    created_at TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
